### Pandas Class 2 ###

In [1]:
import pandas as pd

In [5]:
data = pd.read_excel("employee.xlsx")

### Dealing Rows

In [9]:
# jab khud ke index dene ho usse labels kehte hai
# data.Serial
# agar index by default nahi chahiye to ye approach use krege
data = pd.read_excel("employee.xlsx",index_col="Serial")
data

        Emp_ID Designation  Department   Age    Salary
Serial
1         1101     Manager    Accounts  50.0  200000.0
2         1107     Officer          IT  30.0   80000.0
3         1203     Officer          HR  28.0       NaN
4         1005     Manager          HR  45.0  120000.0
5         2123  Office Boy    Accounts  27.0   45000.0
6         2451  Accountant         NaN  34.0  100000.0
7         1111  Accountant    Accounts   NaN  110000.0
8         1001     Officer          IT  25.0   75000.0
9         1234     Manager          IT  23.0       NaN
10        2156    Engineer  Production  45.0   89000.0
11        6543     Officer  Production  29.0  100000.0
12        3214  Accountant     Account  49.0  123000.0
13        2156    Engineer  Production  45.0   89000.0
14        1098     Officer          IT  25.0  100000.0
15        2912     Officer          IT  31.0   90000.0
16        1222     Officer         NaN  25.0       NaN
17        2156    Engineer  Production  45.0   89000.0
18        2123  Office Boy    Accounts  27.0   45000.0
19        2156    Engineer  Production  45.0   89000.0
20        6543     Officer  Production  29.0  100000.0
21        3214  Accountant     Account  49.0  123000.0
22        3214  Accountant     Account  49.0  123000.0
23        2156    Engineer  Production  45.0   89000.0
24        1098     Officer          IT  25.0  100000.0

In [12]:
data.head(10)

        Emp_ID Designation  Department   Age    Salary
Serial
1         1101     Manager    Accounts  50.0  200000.0
2         1107     Officer          IT  30.0   80000.0
3         1203     Officer          HR  28.0       NaN
4         1005     Manager          HR  45.0  120000.0
5         2123  Office Boy    Accounts  27.0   45000.0
6         2451  Accountant         NaN  34.0  100000.0
7         1111  Accountant    Accounts   NaN  110000.0
8         1001     Officer          IT  25.0   75000.0
9         1234     Manager          IT  23.0       NaN
10        2156    Engineer  Production  45.0   89000.0

In [19]:
# data[row:col] ---> str end
# iloc => integer loc
# rows ko slice or column ko slice ek sath kre to iloc use krte
data.iloc[2:5, 1:4]
# column index starts from 0 too

       Designation Department   Age
Serial
3          Officer         HR  28.0
4          Manager         HR  45.0
5       Office Boy   Accounts  27.0

    -.loc is label-based: You select data using the explicit names of the rows or columns.

    -.iloc is integer-position-based: You select data using the implicit 0-indexed position (like a standard Python list), completely ignoring the actual names.

In [20]:
data.columns
# 0-1 index start hoti hai

Index(['Emp_ID', 'Designation', 'Department', 'Age', 'Salary'], dtype='str')

In [23]:
data

        Emp_ID Designation  Department   Age    Salary
Serial
1         1101     Manager    Accounts  50.0  200000.0
2         1107     Officer          IT  30.0   80000.0
3         1203     Officer          HR  28.0       NaN
4         1005     Manager          HR  45.0  120000.0
5         2123  Office Boy    Accounts  27.0   45000.0
6         2451  Accountant         NaN  34.0  100000.0
7         1111  Accountant    Accounts   NaN  110000.0
8         1001     Officer          IT  25.0   75000.0
9         1234     Manager          IT  23.0       NaN
10        2156    Engineer  Production  45.0   89000.0
11        6543     Officer  Production  29.0  100000.0
12        3214  Accountant     Account  49.0  123000.0
13        2156    Engineer  Production  45.0   89000.0
14        1098     Officer          IT  25.0  100000.0
15        2912     Officer          IT  31.0   90000.0
16        1222     Officer         NaN  25.0       NaN
17        2156    Engineer  Production  45.0   89000.0
18        2123  Office Boy    Accounts  27.0   45000.0
19        2156    Engineer  Production  45.0   89000.0
20        6543     Officer  Production  29.0  100000.0
21        3214  Accountant     Account  49.0  123000.0
22        3214  Accountant     Account  49.0  123000.0
23        2156    Engineer  Production  45.0   89000.0
24        1098     Officer          IT  25.0  100000.0

In [25]:
# using default to kill confusion
data = pd.read_excel("employee.xlsx")
data

    Serial  Emp_ID Designation  Department   Age    Salary
0        1    1101     Manager    Accounts  50.0  200000.0
1        2    1107     Officer          IT  30.0   80000.0
2        3    1203     Officer          HR  28.0       NaN
3        4    1005     Manager          HR  45.0  120000.0
4        5    2123  Office Boy    Accounts  27.0   45000.0
5        6    2451  Accountant         NaN  34.0  100000.0
6        7    1111  Accountant    Accounts   NaN  110000.0
7        8    1001     Officer          IT  25.0   75000.0
8        9    1234     Manager          IT  23.0       NaN
9       10    2156    Engineer  Production  45.0   89000.0
10      11    6543     Officer  Production  29.0  100000.0
11      12    3214  Accountant     Account  49.0  123000.0
12      13    2156    Engineer  Production  45.0   89000.0
13      14    1098     Officer          IT  25.0  100000.0
14      15    2912     Officer          IT  31.0   90000.0
15      16    1222     Officer         NaN  25.0       NaN
16      17    2156    Engineer  Production  45.0   89000.0
17      18    2123  Office Boy    Accounts  27.0   45000.0
18      19    2156    Engineer  Production  45.0   89000.0
19      20    6543     Officer  Production  29.0  100000.0
20      21    3214  Accountant     Account  49.0  123000.0
21      22    3214  Accountant     Account  49.0  123000.0
22      23    2156    Engineer  Production  45.0   89000.0
23      24    1098     Officer          IT  25.0  100000.0

In [29]:
data.iloc[1:11,3:4] #(range-1 hota hai)

    Department
1           IT
2           HR
3           HR
4     Accounts
5          NaN
6     Accounts
7           IT
8           IT
9   Production
10  Production

In [33]:
data.loc[1:6,"Emp_ID":"Department"]

   Emp_ID Designation Department
1    1107     Officer         IT
2    1203     Officer         HR
3    1005     Manager         HR
4    2123  Office Boy   Accounts
5    2451  Accountant        NaN
6    1111  Accountant   Accounts

In [36]:
data.Designation=="Accountant"

0     False
1     False
2     False
3     False
4     False
5      True
6      True
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
21     True
22    False
23    False
Name: Designation, dtype: bool

In [38]:
data[data.Designation == "Manager"]

   Serial  Emp_ID Designation Department   Age    Salary
0       1    1101     Manager   Accounts  50.0  200000.0
3       4    1005     Manager         HR  45.0  120000.0
8       9    1234     Manager         IT  23.0       NaN

In [44]:
data[data.Department=="IT"]

    Serial  Emp_ID Designation Department   Age    Salary
1        2    1107     Officer         IT  30.0   80000.0
7        8    1001     Officer         IT  25.0   75000.0
8        9    1234     Manager         IT  23.0       NaN
13      14    1098     Officer         IT  25.0  100000.0
14      15    2912     Officer         IT  31.0   90000.0
23      24    1098     Officer         IT  25.0  100000.0

In [49]:
data[data.Salary >= 100000]

    Serial  Emp_ID Designation  Department   Age    Salary
0        1    1101     Manager    Accounts  50.0  200000.0
3        4    1005     Manager          HR  45.0  120000.0
5        6    2451  Accountant         NaN  34.0  100000.0
6        7    1111  Accountant    Accounts   NaN  110000.0
10      11    6543     Officer  Production  29.0  100000.0
11      12    3214  Accountant     Account  49.0  123000.0
13      14    1098     Officer          IT  25.0  100000.0
19      20    6543     Officer  Production  29.0  100000.0
20      21    3214  Accountant     Account  49.0  123000.0
21      22    3214  Accountant     Account  49.0  123000.0
23      24    1098     Officer          IT  25.0  100000.0

In [57]:
# knowledge solution
cols_nan = data.loc[data['Salary'].isna()]
data['Salary'] = data['Salary'].fillna(10000)
cols_nan
data

    Serial  Emp_ID Designation  Department   Age    Salary
0        1    1101     Manager    Accounts  50.0  200000.0
1        2    1107     Officer          IT  30.0   80000.0
2        3    1203     Officer          HR  28.0   10000.0
3        4    1005     Manager          HR  45.0  120000.0
4        5    2123  Office Boy    Accounts  27.0   45000.0
5        6    2451  Accountant         NaN  34.0  100000.0
6        7    1111  Accountant    Accounts   NaN  110000.0
7        8    1001     Officer          IT  25.0   75000.0
8        9    1234     Manager          IT  23.0   10000.0
9       10    2156    Engineer  Production  45.0   89000.0
10      11    6543     Officer  Production  29.0  100000.0
11      12    3214  Accountant     Account  49.0  123000.0
12      13    2156    Engineer  Production  45.0   89000.0
13      14    1098     Officer          IT  25.0  100000.0
14      15    2912     Officer          IT  31.0   90000.0
15      16    1222     Officer         NaN  25.0   10000.0
16      17    2156    Engineer  Production  45.0   89000.0
17      18    2123  Office Boy    Accounts  27.0   45000.0
18      19    2156    Engineer  Production  45.0   89000.0
19      20    6543     Officer  Production  29.0  100000.0
20      21    3214  Accountant     Account  49.0  123000.0
21      22    3214  Accountant     Account  49.0  123000.0
22      23    2156    Engineer  Production  45.0   89000.0
23      24    1098     Officer          IT  25.0  100000.0

In [64]:
data[data.Designation=="Officer"]['Department']
# ek or square bracket lagadiya multiple columns nahi asakte
data[data.Designation=="Officer"][['Emp_ID','Salary','Department']]

    Emp_ID    Salary  Department
1     1107   80000.0          IT
2     1203   10000.0          HR
7     1001   75000.0          IT
10    6543  100000.0  Production
13    1098  100000.0          IT
14    2912   90000.0          IT
15    1222   10000.0         NaN
19    6543  100000.0  Production
23    1098  100000.0          IT

In [68]:
data[(data.Designation == "Officer") & (data.Department == "HR")]

   Serial  Emp_ID Designation Department   Age   Salary
2       3    1203     Officer         HR  28.0  10000.0

In [69]:
data[data.Salary==data.Salary.max()]

   Serial  Emp_ID Designation Department   Age    Salary
0       1    1101     Manager   Accounts  50.0  200000.0

In [72]:
data[(data.Department == "IT") | (data.Designation == "Officer")]

    Serial  Emp_ID Designation  Department   Age    Salary
1        2    1107     Officer          IT  30.0   80000.0
2        3    1203     Officer          HR  28.0   10000.0
7        8    1001     Officer          IT  25.0   75000.0
8        9    1234     Manager          IT  23.0   10000.0
10      11    6543     Officer  Production  29.0  100000.0
13      14    1098     Officer          IT  25.0  100000.0
14      15    2912     Officer          IT  31.0   90000.0
15      16    1222     Officer         NaN  25.0   10000.0
19      20    6543     Officer  Production  29.0  100000.0
23      24    1098     Officer          IT  25.0  100000.0

In [74]:
data['column_age_salary_multiply'] = data.Age*data.Salary
data

,Serial,Emp_ID,Designation,Department,Age,Salary,column_age_salary_multiply
0,1,1101,Manager,Accounts,50.0,200000.0,10000000.0
1,2,1107,Officer,IT,30.0,80000.0,2400000.0
2,3,1203,Officer,HR,28.0,10000.0,280000.0
3,4,1005,Manager,HR,45.0,120000.0,5400000.0
4,5,2123,Office Boy,Accounts,27.0,45000.0,1215000.0
5,6,2451,Accountant,NaN,34.0,100000.0,3400000.0
6,7,1111,Accountant,Accounts,NaN,110000.0,NaN
7,8,1001,Officer,IT,25.0,75000.0,1875000.0
8,9,1234,Manager,IT,23.0,10000.0,230000.0
9,10,2156,Engineer,Production,45.0,89000.0,4005000.0
10,11,6543,Officer,Production,29.0,100000.0,2900000.0
11,12,3214,Accountant,Account,49.0,123000.0,6027000.0
12,13,2156,Engineer,Production,45.0,89000.0,4005000.0
13,14,1098,Officer,IT,25.0,100000.0,2500000.0
14,15,2912,Officer,IT,31.0,90000.0,2790000.0
15,16,1222,Officer,NaN,25.0,10000.0,250000.0
16,17,2156,Engineer,Production,45.0,89000.0,4005000.0
17,18,2123,Office Boy,Accounts,27.0,45000.0,1215000.0
18,19,2156,Engineer,Production,45.0,89000.0,4005000.0
19,20,6543,Officer,Production,29.0,100000.0,2900000.0
20,21,3214,Accountant,Account,49.0,123000.0,6027000.0
21,22,3214,Accountant,Account,49.0,123000.0,6027000.0
22,23,2156,Engineer,Production,45.0,89000.0,4005000.0
23,24,1098,Officer,IT,25.0,100000.0,2500000.0

In [79]:
data[(data.Designation=="Officer") & (data.Department=="HR") & (data.Age==28)]

,Serial,Emp_ID,Designation,Department,Age,Salary,column_age_salary_multiply
2,3,1203,Officer,HR,28.0,10000.0,280000.0

### Movie Data

In [81]:
data.Designation.value_counts()

Designation
Officer       9
Accountant    5
Engineer      5
Manager       3
Office Boy    2
Name: count, dtype: int64

In [83]:
data.Designation.value_counts().index, data.Designation.value_counts().values

(Index(['Officer', 'Accountant', 'Engineer', 'Manager', 'Office Boy'], dtype='str', name='Designation'),
 array([9, 5, 5, 3, 2]))