### Pandas:
    - Python ki library hai
    - Data Cleaning me kam ati hai
    - Backend pr numpy hoti

### Pandas Data Structure
    - Pandas Series
    - Pandas Dataframe

**Its usually Installed in Python Already If not installed one can use pip install pandas**

### Series:
    -We work on one column only (univariation):

In [1]:
import pandas as pd
s1 = pd.Series([1,2,3,4,5,6])
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

components : Index

    Jo by default hote hai left side pr or right side pr jo arhi hoti hai woh values hoti hai
    Teesri cheez hamare pass jo hoti hai woh hoti hai data type

In [2]:
s2 = pd.Series([1,2,3,4,5.5])
s2

0    1.0
1    2.0
2    3.0
3    4.0
4    5.5
dtype: float64

In [3]:
type(s2)

pandas.core.series.Series

In [4]:
s2.values
# to detemine value

array([1. , 2. , 3. , 4. , 5.5])

In [5]:
s2.dtype

dtype('float64')

In [6]:
s2.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
s2.shape

(5,)

**Difference between type and dtype is type tells what is it numpy or panadas but dtype tells what the type of data is stored inside those containers**

In [8]:
# s3 = pd.Series([120, 80, 30, 90, 50], index=["Mango", "Apple", "Banana", "Grapes", "Orange"])
# s3
s4 = pd.Series([120, 80, 30, 90, 50],["Mango", "Apple", "Banana", "Grapes", "Orange"])
s4

Mango     120
Apple      80
Banana     30
Grapes     90
Orange     50
dtype: int64

### Indexing

In [9]:
s4["Mango"]

np.int64(120)

In [10]:
s4["Apple"]

np.int64(80)

### SLICING

In [11]:
s4["Mango":]

Mango     120
Apple      80
Banana     30
Grapes     90
Orange     50
dtype: int64

In [12]:
s4["Mango":"Grapes"]

Mango     120
Apple      80
Banana     30
Grapes     90
dtype: int64

In [13]:
s4.shape

(5,)

In [14]:
s4.dtype

dtype('int64')

In [15]:
data_1 = pd.Series([100,200,300,400,"Mango"])
data_1
# string value jo bhi ho usse object kahege

0      100
1      200
2      300
3      400
4    Mango
dtype: object

### Data Frames
    -The one in tabular form

In [16]:
data = {
    "Name" : ["Shahzaib","Munawar"],
    "Age" : [19,20],
    "City" : ["Karachi","Karachi"]
}
df = pd.DataFrame(data)
df

       Name  Age     City
0  Shahzaib   19  Karachi
1   Munawar   20  Karachi

In [36]:
data = {
    "Name" : ["Shahzaib","Munawar"],
    "Age" : [19,20],
    "City" : ["Karachi","Karachi"],
    "Address" : ["Lasbella","Patel Para"],
    "Degree" : ["BSCS","BSCS"],
    "Marks" : [220,230]
    
}
df = pd.DataFrame(data)
df

       Name  Age     City     Address Degree  Marks
0  Shahzaib   19  Karachi    Lasbella   BSCS    220
1   Munawar   20  Karachi  Patel Para   BSCS    230

### Accessing elements
    -Access Columns
    -Access Multiple Columns 
    -Add Columns
    -Delete Columns

In [24]:
data["Name"]
df.Name

0    Shahzaib
1     Munawar
Name: Name, dtype: object

In [25]:
# column access (works if name is a valid identifier)
df.Name        # returns a Series for the "Name" column

# always-safe bracket access
df['Name']     
df[['Name', 'Age']]

# row access
df.loc[0]      # by label
df.iloc[0]     # by integer position

# for the original dict use bracket access (dicts have no dot-access)
data['Name']

['Shahzaib', 'Munawar']

In [27]:
df.Age

0    19
1    20
Name: Age, dtype: int64

In [29]:
df["Age"]

0    19
1    20
Name: Age, dtype: int64

In [30]:
df["Address"]

0      Lasbella
1    Patel Para
Name: Address, dtype: object

In [34]:
df[["Name","Address"]]

       Name     Address
0  Shahzaib    Lasbella
1   Munawar  Patel Para

### Adding a column

In [59]:
df["Status"]=["Pass" if a >= 50.0 else "Fail" for a in df.Percentage]
df

       Name  Age     City     Address Degree  Marks Status  Percentage
0  Shahzaib   19  Karachi    Lasbella   BSCS    220   Pass        88.0
1   Munawar   20  Karachi  Patel Para   BSCS    230   Pass        92.0

In [60]:
df["Sample"] = "Teesre pr"
df

,Name,Age,City,Address,Degree,Marks,Status,Percentage,Sample
0,Shahzaib,19,Karachi,Lasbella,BSCS,220,Pass,88.0,Teesre pr
1,Munawar,20,Karachi,Patel Para,BSCS,230,Pass,92.0,Teesre pr

### Delete Column

In [61]:
df

,Name,Age,City,Address,Degree,Marks,Status,Percentage,Sample
0,Shahzaib,19,Karachi,Lasbella,BSCS,220,Pass,88.0,Teesre pr
1,Munawar,20,Karachi,Patel Para,BSCS,230,Pass,92.0,Teesre pr

In [62]:
# deletion
del df["Sample"]
df

       Name  Age     City     Address Degree  Marks Status  Percentage
0  Shahzaib   19  Karachi    Lasbella   BSCS    220   Pass        88.0
1   Munawar   20  Karachi  Patel Para   BSCS    230   Pass        92.0

In [63]:
# set total marks (adjust as needed)
total_marks = 250
# calculate percentage and round to 2 decimals
df["Percentage"] = (df["Marks"] / total_marks) * 100
df["Percentage"] = df["Percentage"].round(2)
df

       Name  Age     City     Address Degree  Marks Status  Percentage
0  Shahzaib   19  Karachi    Lasbella   BSCS    220   Pass        88.0
1   Munawar   20  Karachi  Patel Para   BSCS    230   Pass        92.0

### Adding Grade using 
    -List Comprehension
    -Function

In [66]:
df["Grade"] = [
    "A" if a >= 90
      else "B" if a >= 80
        else "C" if a >= 70
          else "D" if a >=60
            else "F"
              for a in df["Percentage"]]
df

       Name  Age     City     Address Degree  Marks Status  Percentage Grade
0  Shahzaib   19  Karachi    Lasbella   BSCS    220   Pass        88.0     B
1   Munawar   20  Karachi  Patel Para   BSCS    230   Pass        92.0     A

    -USING FUNCTION

In [69]:
def calculateGrade(percentage):
    if percentage >= 90:
        return "A+"
    elif percentage >= 80:
      return "A"
    elif percentage >= 70:
       return "B"
    elif percentage >= 60:
       return "C"
    elif percentage >= 50:
       return "D"
    else:
       return "F"
    
df["Grade"] = df["Percentage"].apply(calculateGrade) 
df

       Name  Age     City     Address Degree  Marks Status  Percentage Grade
0  Shahzaib   19  Karachi    Lasbella   BSCS    220   Pass        88.0     A
1   Munawar   20  Karachi  Patel Para   BSCS    230   Pass        92.0    A+

In [72]:
data1 = pd.read_excel("employee.xlsx")
data1

    Serial  Emp_ID Designation  Department   Age    Salary
0        1    1101     Manager    Accounts  50.0  200000.0
1        2    1107     Officer          IT  30.0   80000.0
2        3    1203     Officer          HR  28.0       NaN
3        4    1005     Manager          HR  45.0  120000.0
4        5    2123  Office Boy    Accounts  27.0   45000.0
5        6    2451  Accountant         NaN  34.0  100000.0
6        7    1111  Accountant    Accounts   NaN  110000.0
7        8    1001     Officer          IT  25.0   75000.0
8        9    1234     Manager          IT  23.0       NaN
9       10    2156    Engineer  Production  45.0   89000.0
10      11    6543     Officer  Production  29.0  100000.0
11      12    3214  Accountant     Account  49.0  123000.0
12      13    2156    Engineer  Production  45.0   89000.0
13      14    1098     Officer          IT  25.0  100000.0
14      15    2912     Officer          IT  31.0   90000.0
15      16    1222     Officer         NaN  25.0       NaN
16      17    2156    Engineer  Production  45.0   89000.0
17      18    2123  Office Boy    Accounts  27.0   45000.0
18      19    2156    Engineer  Production  45.0   89000.0
19      20    6543     Officer  Production  29.0  100000.0
20      21    3214  Accountant     Account  49.0  123000.0
21      22    3214  Accountant     Account  49.0  123000.0
22      23    2156    Engineer  Production  45.0   89000.0
23      24    1098     Officer          IT  25.0  100000.0

In [ ]:
data1.head()
# returns starting 5 values

   Serial  Emp_ID Designation Department   Age    Salary
0       1    1101     Manager   Accounts  50.0  200000.0
1       2    1107     Officer         IT  30.0   80000.0
2       3    1203     Officer         HR  28.0       NaN
3       4    1005     Manager         HR  45.0  120000.0
4       5    2123  Office Boy   Accounts  27.0   45000.0

In [ ]:
data1.tail()
# returns last 5 values  by default we can configure it by adding value in the (value)

    Serial  Emp_ID Designation  Department   Age    Salary
19      20    6543     Officer  Production  29.0  100000.0
20      21    3214  Accountant     Account  49.0  123000.0
21      22    3214  Accountant     Account  49.0  123000.0
22      23    2156    Engineer  Production  45.0   89000.0
23      24    1098     Officer          IT  25.0  100000.0

In [ ]:
data1.sample(3)
# gives random value from the data (we can add how many values we want in here)

    Serial  Emp_ID Designation Department   Age   Salary
14      15    2912     Officer         IT  31.0  90000.0
2        3    1203     Officer         HR  28.0      NaN
4        5    2123  Office Boy   Accounts  27.0  45000.0

In [ ]:
data1.info()
# gives info for the data1 table

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Serial       24 non-null     int64
 1   Emp_ID       24 non-null     int64
 2   Designation  24 non-null     object
 3   Department   22 non-null     object
 4   Age          23 non-null     float64
 5   Salary       21 non-null     float64
dtypes: float64(2), int64(2), object(2)
memory usage: 1.3+ KB

In [88]:
data1.Department

0       Accounts
1             IT
2             HR
3             HR
4       Accounts
5            NaN
6       Accounts
7             IT
8             IT
9     Production
10    Production
11       Account
12    Production
13            IT
14            IT
15           NaN
16    Production
17      Accounts
18    Production
19    Production
20       Account
21       Account
22    Production
23            IT
Name: Department, dtype: object

In [90]:
data1.Department.isna().sum()

np.int64(2)